services:
 tgbot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - TELEGRAM_LOCAL
      # - TELEGRAM_VERBOSITY
    networks:
      - tg
 music:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - data:/data
      - ./cookies.txt:/cookies.txt
    environment:
      - TOKEN_STORAGE_PATH=/data
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SPOTIFY_REDIRECT_URL
      - TELEGRAM_API_TOKEN
      - TELEGRAM_BOT_USERNAME
      - TELEGRAM_BASE_SCHEMA
      - TELEGRAM_BASE_URL
      - TELEGRAM_BASE_PORT
      - YTDL_LOCATION
    depends_on:
      - tgbot-api
    networks:
      - tg

volumes:
  data:

networks:
  tg:
