services:
 tgbot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - TELEGRAM_LOCAL
      # - TELEGRAM_VERBOSITY
    networks:
      - tg
 music:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - data:/data
      - ./cookies.txt:/cookies.txt
    environment:
      - TELEGRAM_API_TOKEN
      - TELEGRAM_BOT_USERNAME
      - TELEGRAM_BASE_SCHEMA
      - TELEGRAM_BASE_URL
      - TELEGRAM_BASE_PORT
      - YTDL_LOCATION
      - ERROR_NOTIFICATION_TELEGRAM_ID
      - YTDL_PROXY
      - YTDL_PROXY_URL_CONTAINS
    depends_on:
      - tgbot-api
    networks:
      - tg

volumes:
  data:

networks:
  tg:
